# Site settings
author: Alexander Hulteng
title: Carry me to codeland
header-img: img/home-bg.png
email: alexanderhulteng@gmail.com
copyright_name: Alexander Hulteng
description: > # this means to ignore newlines until "baseurl:"
  My Memoirs
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alexanderhulteng

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
